# Default configuration for SmolVLA Federated Learning
model:
  name: "lerobot/smolvla_base"
  device: "auto"  # auto, cpu, or cuda

training:
  num_rounds: 50  # Reduced for initial testing
  fraction_fit: 0.8
  fraction_evaluate: 0.8
  local_epochs: 5  # Start with fewer epochs for testing
  batch_size: 4
  learning_rate: 1e-4
  server_device: "auto"
  use_wandb: true

federation:
  num_partitions: 10  # Number of data partitions
  num_supernodes: 10  # Number of clients

dataset:
  name: "lerobot/so100"
  delta_timestamps:
    observation.image: [-0.1, 0.0]
    observation.state: [-0.1, 0.0]
    action: [-0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4]

# Policy configuration
policy:
  vla:
    model_name: "lerobot/smolvla_base"
    device: "auto"