name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: ${{ matrix.test-type }} UnitTests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - test-type: all
            python-version: '3.10'
            test-path: tests/unit
            cov-fail-under: 30
            parallel: 0
            flags: unit-tests

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.ci
        load: true
        tags: zk0-ci:latest

    - name: Run ${{ matrix.test-type }} tests in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -e CUDA_VISIBLE_DEVICES="" \
          zk0-ci:latest \
          bash -c "
            cd /workspace &&
            export CI=true &&
            uv pip install -e '.[test]' &&
            pytest ${{ matrix.test-path }} -x --tb=short --durations=10 --no-cov -n ${{ matrix.parallel }}
          "
