name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: ${{ matrix.test-type }} UnitTests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - test-type: all
            python-version: '3.10'
            test-path: tests/unit
            cov-fail-under: 30
            parallel: auto
            flags: unit-tests

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.ci
        load: true
        tags: zk0-ci:latest

    - name: Run ${{ matrix.test-type }} tests in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -v /tmp/coverage:/coverage \
          -e CUDA_VISIBLE_DEVICES="" \
          zk0-ci:latest \
          bash -c "
            cd /workspace &&
            export CI=true &&
            uv pip install -e '.[test]' &&
            pytest ${{ matrix.test-path }} -x --tb=short --durations=10 \
              --cov=src --cov-report=term-missing --cov-report=xml \
              --cov-fail-under=${{ matrix.cov-fail-under }} -n ${{ matrix.parallel }} &&
            cp coverage.xml /coverage/
          "

    - name: Upload coverage artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.test-type }}-test-coverage
        path: /tmp/coverage/coverage.xml

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: /tmp/coverage/coverage.xml
        flags: ${{ matrix.flags }}
        fail_ci_if_error: false